// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVr9n70pT3iC2T4KSrt2nMZI4ezGJONNc',
    appId: '1:87170443990:web:02572fcbb3f1891b593777',
    messagingSenderId: '87170443990',
    projectId: 'uniroute-36e10',
    authDomain: 'uniroute-36e10.firebaseapp.com',
    storageBucket: 'uniroute-36e10.firebasestorage.app',
    measurementId: 'G-HVG6ZY3RLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkJX_k9KCRF8aXNHdA1nlzhfowlFRnIs',
    appId: '1:87170443990:android:753be3a00c10061c593777',
    messagingSenderId: '87170443990',
    projectId: 'uniroute-36e10',
    storageBucket: 'uniroute-36e10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD1Hdu-a3RIueNv_B7gGaGKV2W-IPJvYY',
    appId: '1:87170443990:ios:005d3ffcd3d3e132593777',
    messagingSenderId: '87170443990',
    projectId: 'uniroute-36e10',
    storageBucket: 'uniroute-36e10.firebasestorage.app',
    iosClientId: '87170443990-7olu0p0hs5ksqnd4ufknfa958sofatmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniroute',
  );
}
